/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v6.0
processor: LPC54114J256
package_id: LPC54114J256BD64
mcu_data: ksdk2_0
processor_version: 6.0.2
board: LPCXpresso54114
functionalGroups:
- name: BOARD_InitPeripherals
  called_from_default_init: true
  selectedCore: cm4
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'msg'
- type_id: 'msg_6e2baaf3b97dbeef01c0043275f9a0e7'
- global_messages: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * CTIMER_1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CTIMER_1'
- type: 'ctimer'
- mode: 'PWM'
- type_id: 'ctimer_c8b90232d8b6318ba1dac2cf08fb5f4a'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CTIMER1'
- config_sets:
  - fsl_ctimer:
    - ctimerConfig:
      - mode: 'kCTIMER_TimerMode'
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'BOARD_BootClockFROHF96M'
      - timerPrescaler: '256'
    - EnableTimerInInit: 'false'
    - pwmConfig:
      - pwmPeriodValueStr: '4000hz'
      - enableInterrupt: 'false'
      - pwmChannels:
        - 0:
          - pwmChannelPrefixId: 'PWM_0'
          - pwmChannel: 'kCTIMER_Match_0'
          - pwmDutyValueStr: '150us'
          - enableInterrupt: 'false'
    - interruptCallbackConfig:
      - interrupt:
        - IRQn: 'CTIMER0_IRQn'
        - enable_priority: 'false'
        - priority: '0'
      - callback: 'kCTIMER_NoCallback'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const ctimer_config_t CTIMER_1_config = {
  .mode = kCTIMER_TimerMode,
  .input = kCTIMER_Capture_0,
  .prescale = 255
};

void CTIMER_1_init(void) {
  /* CTIMER1 peripheral initialization */
  CTIMER_Init(CTIMER_1_PERIPHERAL, &CTIMER_1_config);
  /* PWM channel 0 of CTIMER1 peripheral initialization */
  CTIMER_SetupPwmPeriod(CTIMER_1_PERIPHERAL, CTIMER_1_PWM_0_CHANNEL, CTIMER_1_PWM_PERIOD, CTIMER_1_PWM_0_DUTY, false);
}

/***********************************************************************************************************************
 * I2C_7 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'I2C_7'
- type: 'flexcomm_i2c'
- mode: 'I2C_Polling'
- type_id: 'flexcomm_i2c_567d1a9d97c12e5d39b00259c3436dc4'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM7'
- config_sets:
  - fsl_i2c:
    - i2c_mode: 'kI2C_Master'
    - clockSource: 'FXCOMFunctionClock'
    - clockSourceFreq: 'BOARD_BootClockFROHF96M'
    - i2c_master_config:
      - enableMaster: 'true'
      - baudRate_Bps: '100000'
      - enableTimeout: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const i2c_master_config_t I2C_7_config = {
  .enableMaster = true,
  .baudRate_Bps = 100000,
  .enableTimeout = false
};

void I2C_7_init(void) {
  RESET_PeripheralReset( kFC7_RST_SHIFT_RSTn);
  /* Initialization function */
  I2C_MasterInit(I2C_7_PERIPHERAL, &I2C_7_config, I2C_7_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * USART_0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'USART_0'
- type: 'flexcomm_usart'
- mode: 'polling'
- type_id: 'flexcomm_usart_c0a0c6d3d3ef57701b439b00070052a8'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM0'
- config_sets:
  - usartConfig_t:
    - usartConfig:
      - clockSource: 'FXCOMFunctionClock'
      - clockSourceFreq: 'BOARD_BootClockFROHF96M'
      - baudRate_Bps: '115200'
      - syncMode: 'kUSART_SyncModeDisabled'
      - parityMode: 'kUSART_ParityDisabled'
      - stopBitCount: 'kUSART_OneStopBit'
      - bitCountPerChar: 'kUSART_8BitsPerChar'
      - loopback: 'false'
      - txWatermark: 'kUSART_TxFifo0'
      - rxWatermark: 'kUSART_RxFifo1'
      - enableRx: 'true'
      - enableTx: 'true'
      - clockPolarity: 'kUSART_RxSampleOnFallingEdge'
      - enableContinuousSCLK: 'false'
    - quick_selection: 'QuickSelection1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const usart_config_t USART_0_config = {
  .baudRate_Bps = 115200,
  .syncMode = kUSART_SyncModeDisabled,
  .parityMode = kUSART_ParityDisabled,
  .stopBitCount = kUSART_OneStopBit,
  .bitCountPerChar = kUSART_8BitsPerChar,
  .loopback = false,
  .txWatermark = kUSART_TxFifo0,
  .rxWatermark = kUSART_RxFifo1,
  .enableRx = true,
  .enableTx = true,
  .clockPolarity = kUSART_RxSampleOnFallingEdge,
  .enableContinuousSCLK = false
};

void USART_0_init(void) {
  /* Reset FLEXCOMM device */
  RESET_PeripheralReset(kFC0_RST_SHIFT_RSTn);
  USART_Init(USART_0_PERIPHERAL, &USART_0_config, USART_0_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * CTIMER_0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'CTIMER_0'
- type: 'ctimer'
- mode: 'Capture_Match'
- type_id: 'ctimer_c8b90232d8b6318ba1dac2cf08fb5f4a'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'CTIMER0'
- config_sets:
  - fsl_ctimer:
    - ctimerConfig:
      - mode: 'kCTIMER_TimerMode'
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'BOARD_BootClockFROHF96M'
      - timerPrescaler: '1'
    - EnableTimerInInit: 'false'
    - matchChannels: []
    - interruptCallbackConfig:
      - interrupt:
        - IRQn: 'CTIMER0_IRQn'
        - enable_priority: 'false'
        - priority: '0'
      - callback: 'kCTIMER_NoCallback'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const ctimer_config_t CTIMER_0_config = {
  .mode = kCTIMER_TimerMode,
  .input = kCTIMER_Capture_0,
  .prescale = 0
};

void CTIMER_0_init(void) {
  /* CTIMER0 peripheral initialization */
  CTIMER_Init(CTIMER_0_PERIPHERAL, &CTIMER_0_config);
}

/***********************************************************************************************************************
 * MRT_1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'MRT_1'
- type: 'mrt'
- mode: 'general_config'
- type_id: 'mrt_ec4ff9f008b2eee803e5f398b3b3325f'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'MRT0'
- config_sets:
  - fsl_mrt:
    - mrtOperationMode: 'HSM'
    - clockSettingMRT:
      - clockSource: 'BusInterfaceClock'
      - clockSourceFreq: 'BOARD_BootClockFROHF96M'
    - mrtChannels:
      - 0:
        - mrtChannelPrefixID: 'Channel_0'
        - channelNumber: 'kMRT_Channel_0'
        - timerMode: 'kMRT_RepeatMode'
        - timerValueStr: '100ms'
        - startTimer: 'true'
        - enableInterruptRequest: 'true'
      - 1:
        - mrtChannelPrefixID: 'Channel_1'
        - channelNumber: 'kMRT_Channel_1'
        - timerMode: 'kMRT_RepeatMode'
        - timerValueStr: '10ms'
        - startTimer: 'true'
        - enableInterruptRequest: 'true'
    - interruptVector:
      - enableInterrupt: 'true'
      - interrupt:
        - IRQn: 'MRT0_IRQn'
        - enable_priority: 'true'
        - priority: '5'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const mrt_config_t MRT_1_config = {
  .enableMultiTask = false
};

void MRT_1_init(void) {
  /* MRT0 peripheral initialization */
  MRT_Init(MRT_1_PERIPHERAL, &MRT_1_config);
  /* MRT channel 0 of MRT0 peripheral initialization */
  MRT_SetupChannelMode(MRT_1_PERIPHERAL, MRT_1_CHANNEL_0, MRT_1_CHANNEL_0_MODE);
  /* MRT channel 1 of MRT0 peripheral initialization */
  MRT_SetupChannelMode(MRT_1_PERIPHERAL, MRT_1_CHANNEL_1, MRT_1_CHANNEL_1_MODE);
  /* MRT channel 0 interrupt of MRT0 peripheral initialization */
  MRT_EnableInterrupts(MRT_1_PERIPHERAL, MRT_1_CHANNEL_0, kMRT_TimerInterruptEnable);
  /* MRT channel 1 interrupt of MRT0 peripheral initialization */
  MRT_EnableInterrupts(MRT_1_PERIPHERAL, MRT_1_CHANNEL_1, kMRT_TimerInterruptEnable);
  /* Interrupt vector MRT0_IRQn priority settings in the NVIC */
  NVIC_SetPriority(MRT_1_IRQN, MRT_1_IRQ_PRIORITY);
  /* Enable interrupt MRT0_IRQn request in the NVIC */
  EnableIRQ(MRT_1_IRQN);
  /* MRT channel 0 start of MRT0 peripheral initialization */
  MRT_StartTimer(MRT_1_PERIPHERAL, MRT_1_CHANNEL_0, MRT_1_CHANNEL_0_TICKS);
  /* MRT channel 1 start of MRT0 peripheral initialization */
  MRT_StartTimer(MRT_1_PERIPHERAL, MRT_1_CHANNEL_1, MRT_1_CHANNEL_1_TICKS);
}

/***********************************************************************************************************************
 * GPIO_1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO_1'
- type: 'lpc_gpio'
- mode: 'GPIO'
- type_id: 'lpc_gpio_8c9ab9b3668a514c1f4609fe43001865'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO'
- config_sets:
  - lpc_gpio: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

void GPIO_1_init(void) {
}

/***********************************************************************************************************************
 * PINT_1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'PINT_1'
- type: 'pint'
- mode: 'interrupt_mode'
- type_id: 'pint_cf4a806bb2a6c1ffced58ae2ed7b43af'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'PINT'
- config_sets:
  - general:
    - interrupt_array:
      - 0:
        - interrupt_id: 'INT_0'
        - interrupt_selection: 'PINT.0'
        - interrupt_type: 'kPINT_PinIntEnableBothEdges'
        - callback_function: 'fan_tacho_int_1'
        - enable_callback: 'true'
        - interrupt:
          - IRQn: 'PIN_INT0_IRQn'
          - enable_priority: 'true'
          - priority: '5'
      - 1:
        - interrupt_id: 'INT_1'
        - interrupt_selection: 'PINT.1'
        - interrupt_type: 'kPINT_PinIntEnableBothEdges'
        - callback_function: 'fan_tacho_int_2'
        - enable_callback: 'true'
        - interrupt:
          - IRQn: 'PIN_INT1_IRQn'
          - enable_priority: 'false'
          - priority: '0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

void PINT_1_init(void) {
  /* PINT_1 initiation  */
  PINT_Init(PINT);
  /* Interrupt vector PIN_INT0_IRQn priority settings in the NVIC */
  NVIC_SetPriority(PINT_1_PINT_0_IRQN, PINT_1_PINT_0_IRQ_PRIORITY);
  /* PINT_1 PINT.0 configuration */
  PINT_PinInterruptConfig(PINT_1_PERIPHERAL, PINT_1_INT_0, kPINT_PinIntEnableBothEdges, fan_tacho_int_1);
  /* PINT_1 PINT.1 configuration */
  PINT_PinInterruptConfig(PINT_1_PERIPHERAL, PINT_1_INT_1, kPINT_PinIntEnableBothEdges, fan_tacho_int_2);
  /* Enable PINT_1 PINT.0 callback */
  PINT_EnableCallbackByIndex(PINT_1_PERIPHERAL, kPINT_PinInt0);
  /* Enable PINT_1 PINT.1 callback */
  PINT_EnableCallbackByIndex(PINT_1_PERIPHERAL, kPINT_PinInt1);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Initialize components */
  CTIMER_1_init();
  I2C_7_init();
  USART_0_init();
  CTIMER_0_init();
  MRT_1_init();
  GPIO_1_init();
  PINT_1_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
