/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO00_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO00_FUNC_ALT1 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO010_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO010_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO010_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO010_SLEW_FAST 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO011_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO011_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO011_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO011_SLEW_FAST 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO012_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO012_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO012_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO012_SLEW_FAST 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO013_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO013_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO013_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO013_SLEW_FAST 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO014_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO014_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO014_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO014_SLEW_FAST 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO015_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 2. */
#define PIO015_FUNC_ALT2 0x02u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO016_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 5. */
#define PIO016_FUNC_ALT5 0x05u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO017_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 5. */
#define PIO017_FUNC_ALT5 0x05u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO018_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO018_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO018_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO018_SLEW_FAST 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO019_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO019_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO019_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO019_SLEW_FAST 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO01_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 1. */
#define PIO01_FUNC_ALT1 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO020_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO020_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO020_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO020_SLEW_FAST 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO021_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO021_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO021_MODE_INACTIVE 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO022_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO022_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO022_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO022_SLEW_FAST 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO023_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO023_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO024_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO024_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO025_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO025_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO02_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO02_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO02_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Standard mode, output slew rate control is enabled.
 * More outputs can be switched simultaneously.
 */
#define PIO02_SLEW_STANDARD 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO031_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO031_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO031_MODE_INACTIVE 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO03_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO03_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO03_MODE_INACTIVE 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO05_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO05_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO05_MODE_INACTIVE 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO06_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO06_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO06_MODE_INACTIVE 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO07_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO07_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO07_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO07_SLEW_FAST 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO08_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO08_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO08_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO08_SLEW_FAST 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO09_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO09_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO09_MODE_INACTIVE 0x00u
/*!
 * @brief
 * Driver slew rate.
 * : Fast mode, slew rate control is disabled.
 * Refer to the appropriate specific device data sheet for details.
 */
#define PIO09_SLEW_FAST 0x01u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO10_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO10_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO110_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO110_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO110_MODE_INACTIVE 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO112_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 3. */
#define PIO112_FUNC_ALT3 0x03u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO112_MODE_INACTIVE 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO11_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO11_FUNC_ALT0 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO13_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO13_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO13_MODE_INACTIVE 0x00u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO14_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 2. */
#define PIO14_FUNC_ALT2 0x02u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO15_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 2. */
#define PIO15_FUNC_ALT2 0x02u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO16_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 7. */
#define PIO16_FUNC_ALT7 0x07u
/*!
 * @brief Select Analog/Digital mode.: Digital mode. */
#define PIO19_DIGIMODE_DIGITAL 0x01u
/*!
 * @brief Selects pin function.: Alternative connection 0. */
#define PIO19_FUNC_ALT0 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO19_MODE_INACTIVE 0x00u

/*! @name PIO1_0 (number 14), Fan Tacho 1
  @{ */
#define BOARD_FAN_TACHO_1_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_FAN_TACHO_1_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_FAN_TACHO_1_PIN 0U    /*!<@brief 1U pin index: 0 */
                                    /* @} */

/*! @name PIO1_1 (number 15), Fan Tacho 2
  @{ */
#define BOARD_FAN_TACHO_2_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_FAN_TACHO_2_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_FAN_TACHO_2_PIN 1U    /*!<@brief 1U pin index: 1 */
                                    /* @} */

/*! @name PIO0_2 (number 36), Reset
  @{ */
#define BOARD_RESET_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_RESET_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_RESET_PIN 2U    /*!<@brief 0U pin index: 2 */
                              /* @} */

/*! @name PIO0_3 (number 37), Power On
  @{ */
#define BOARD_PON_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_PON_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_PON_PIN 3U    /*!<@brief 0U pin index: 3 */
                            /* @} */

/*! @name PIO0_5 (number 39), Link Speed
  @{ */
#define BOARD_LINK_SPEED_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_LINK_SPEED_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_LINK_SPEED_PIN 5U    /*!<@brief 0U pin index: 5 */
                                   /* @} */

/*! @name PIO0_6 (number 40), Test
  @{ */
#define BOARD_TEST_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_TEST_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_TEST_PIN 6U    /*!<@brief 0U pin index: 6 */
                             /* @} */

/*! @name PIO0_7 (number 41), C012 D0
  @{ */
#define BOARD_C012_D0_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_C012_D0_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_C012_D0_PIN 7U    /*!<@brief 0U pin index: 7 */
                                /* @} */

/*! @name PIO0_8 (number 43), C012 D1
  @{ */
#define BOARD_C012_D1_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_C012_D1_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_C012_D1_PIN 8U    /*!<@brief 0U pin index: 8 */
                                /* @} */

/*! @name PIO0_9 (number 44), C012 D2
  @{ */
#define BOARD_C012_D2_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_C012_D2_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_C012_D2_PIN 9U    /*!<@brief 0U pin index: 9 */
                                /* @} */

/*! @name PIO0_10 (number 45), C012 D3
  @{ */
#define BOARD_C012_D3_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_C012_D3_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_C012_D3_PIN 10U   /*!<@brief 0U pin index: 10 */
                                /* @} */

/*! @name PIO0_11 (number 46), C012 D4
  @{ */
#define BOARD_C012_D4_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_C012_D4_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_C012_D4_PIN 11U   /*!<@brief 0U pin index: 11 */
                                /* @} */

/*! @name PIO0_12 (number 47), C012 D5
  @{ */
#define BOARD_C012_D5_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_C012_D5_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_C012_D5_PIN 12U   /*!<@brief 0U pin index: 12 */
                                /* @} */

/*! @name PIO0_13 (number 48), C012 D6
  @{ */
#define BOARD_C012_D6_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_C012_D6_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_C012_D6_PIN 13U   /*!<@brief 0U pin index: 13 */
                                /* @} */

/*! @name PIO0_14 (number 49), C012 D7
  @{ */
#define BOARD_C012_D7_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_C012_D7_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_C012_D7_PIN 14U   /*!<@brief 0U pin index: 14 */
                                /* @} */

/*! @name PIO0_18 (number 58), C012 RS0
  @{ */
#define BOARD_C012_RS0_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_C012_RS0_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_C012_RS0_PIN 18U   /*!<@brief 0U pin index: 18 */
                                 /* @} */

/*! @name PIO0_19 (number 59), C012 RS1
  @{ */
#define BOARD_C012_RS1_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_C012_RS1_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_C012_RS1_PIN 19U   /*!<@brief 0U pin index: 19 */
                                 /* @} */

/*! @name PIO0_20 (number 60), C012 RnotW
  @{ */
#define BOARD_C012_RNOTW_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_C012_RNOTW_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_C012_RNOTW_PIN 20U   /*!<@brief 0U pin index: 20 */
                                   /* @} */

/*! @name PIO0_31 (number 13), Button
  @{ */
#define BOARD_BUTTON_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_BUTTON_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_BUTTON_PIN 31U   /*!<@brief 0U pin index: 31 */
                               /* @} */

/*! @name CTIMER1_MAT0 (number 51), Speaker
  @{ */
/* @} */

/*! @name PIO1_10 (number 30), Analyse
  @{ */
#define BOARD_ANALYSE_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_ANALYSE_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_ANALYSE_PIN 10U   /*!<@brief 1U pin index: 10 */
                                /* @} */

/*! @name PIO1_9 (number 29), Error
  @{ */
#define BOARD_ERROR_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_ERROR_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_ERROR_PIN 9U    /*!<@brief 1U pin index: 9 */
                              /* @} */

/*! @name PIO1_3 (number 17), LED
  @{ */
#define BOARD_LED_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_LED_PORT 1U   /*!<@brief PORT device name: 1U */
#define BOARD_LED_PIN 3U    /*!<@brief 1U pin index: 3 */
                            /* @} */

/*! @name FC0_RXD_SDA_MOSI (number 31), U18[4]/TO_MUX_P0_0-ISP_RX
  @{ */
/* @} */

/*! @name FC0_TXD_SCL_MISO (number 32), U6[4]/U22[3]/P0_1-ISP_TX
  @{ */
/* @} */

/*! @name PIO0_22 (number 63), C012 notCS
  @{ */
#define BOARD_C012_NOTCS_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_C012_NOTCS_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_C012_NOTCS_PIN 22U   /*!<@brief 0U pin index: 22 */
                                   /* @} */

/*! @name PIO0_23 (number 1), C012 Output Int
  @{ */
#define BOARD_C012_OUTPUT_INT_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_C012_OUTPUT_INT_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_C012_OUTPUT_INT_PIN 23U   /*!<@brief 0U pin index: 23 */
                                        /* @} */

/*! @name PIO0_24 (number 2), C012 Input Interrupt
  @{ */
#define BOARD_C012_INPUT_INT_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_C012_INPUT_INT_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_C012_INPUT_INT_PIN 24U   /*!<@brief 0U pin index: 24 */
                                       /* @} */

/*! @name PIO0_25 (number 3), C012 Reset
  @{ */
#define BOARD_C012_RESET_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_C012_RESET_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_C012_RESET_PIN 25U   /*!<@brief 0U pin index: 25 */
                                   /* @} */

/*! @name PIO0_21 (number 61), Debug Pin
  @{ */
#define BOARD_DEBUG_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define BOARD_DEBUG_PORT 0U   /*!<@brief PORT device name: 0U */
#define BOARD_DEBUG_PIN 21U   /*!<@brief 0U pin index: 21 */
                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M4F */

#define IOCON_PIO_DIGITAL_EN 0x80u    /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC1 0x01u         /*!<@brief Selects pin function 1 */
#define IOCON_PIO_INPFILT_OFF 0x0100u /*!<@brief Input filter disabled */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u    /*!<@brief No addition pin function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*! @name FC0_RXD_SDA_MOSI (number 31), U18[4]/TO_MUX_P0_0-ISP_RX
  @{ */
/* @} */

/*! @name FC0_TXD_SCL_MISO (number 32), U6[4]/U22[3]/P0_1-ISP_TX
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins_Core0(void); /* Function assigned for the Cortex-M4F */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
